machine:
  java:
    version: 1.8
    
general:
  branches:
    only:
      - develop # list of branches to build
      
test:
  override:
  - mvn clean verify
  - bash <(curl -s https://codecov.io/bash)
